image: quay.io/epipho/docker:latest

script:
  - env
  - ip addr show

publish:
  docker:
    docker_host: tcp://172.17.8.101:2375
    image_name: quay.io/epipho/test
    username: $$username
    password: $$password
    email: $$email
    registry_login: true
    registry_login_url: quay.io
    tags: ["tag35", "tag36"]